os: linux
language: "minimal"
services:
  - docker

jobs:
  include:
    - name: "checks"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/checks.sh
    -
    - name: "quality"
      script:
        - ./scripts/genenv.sh
        #- docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/coverage.sh
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/duplication.sh
        #- docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/genenv.sh

notifications:
  email: false
